title: NecroMarX
description: Hobbyist
preview:
linktree: https://linktr.ee/NecroMarX
github: https://github.com/NecroMarX
kofi: https://ko-fi.com/necromarx#paypalModal
twitter: https://twitter.com/necromarx
youtube: https://youtube.com/@necromarx
behance: https://behance.net/necromarx
tiktok: https://tiktok.com/@necromarxph
mcpedl: https://mcpedl.com/user/necromarx
discord: NecroMarX#4988
permalink: /:title/
markdown: kramdown
paginate: 5
paginate_path: "/:num/"
show_downloads: false
google_analytics:
theme: jekyll-theme-slate
