title: NecroMarX
description: Hobbyist

home: https://necromarx.github.io/
blogs: /docs/blogs/
addons: /docs/addons/
behance: https://behance.net/necromarx/
about: /docs/about/

permalink: /:title/
markdown: kramdown
paginate: 5
paginate_path: "/:num/"
show_downloads: false
google_analytics:
theme: jekyll-theme-slate
