title: NeKoRoSYS
description: Hobbyist
preview:
linktree: https://linktr.ee/NeKoRoSYS
github: https://github.com/NeKoRoSYS
kofi: https://ko-fi.com/NeKoRoSYS#paypalModal
twitter: https://twitter.com/NeKoRoSYS
youtube: https://youtube.com/@NeKoRoSYS
behance: https://behance.net/NeKoRoSYS
tiktok: https://tiktok.com/@NeKoRoSYS
mcpedl: https://mcpedl.com/user/NeKoRoSYS
discord: NeKoRoSYS#4988
permalink: /:title/
markdown: kramdown
paginate: 5
paginate_path: "/:num/"
show_downloads: false
google_analytics:
theme: jekyll-theme-slate
